[tasks.fmt]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.dev_checks]
dependencies = ["fmt", "clippy", "test"]
